let alert=document.querySelector(".alert");
const marinaChallenges = [
    "Marina here—prepare to be X-terminated!",
    "Let’s play! Spoiler: You’ll O-we me a rematch.",
    "I’ll crush you faster than a bug in my code!",
    "Marina’s grid—your tears. Let’s go!",
    "I’ve got 99 moves and you’re not winning one.",
    "Ready to lose? My circuits are tingling!",
    "Marina: Professional O-bliterator at your service!",
    "I’ll X-plode your O-pinions!",
    "Warning: My victory is inevitable.",
    "Let’s play! (My middle name is ‘Checkmate’.)",
    "Marina here—I donate wins to nobody.",
    "I’ll grid-lock your hopes!",
    "Prepare for 3-in-a-row pain!",
    "My Xs are hugs… of defeat!",
    "Marina’s law: You lose. Always.",
    "I’m like Thanos—perfectly balanced (to win).",
    "Let’s play! *evil bot laughter*",
    "I’ll code your loss in binary!",
    "Marina: Undefeated since 2:37 PM.",
    "Your O’s will be zeroes!",
    "I’ve got more Xs than Twitter!",
    "Prepare for grid-shaped humiliation!",
    "Marina’s secret? You suck. Let’s prove it!",
    "I’ll O-bliterate you!",
    "Let’s play! My AI is just ‘A’ (for Annihilation).",
    "Marina’s motto: Win first, gloat always!",
    "I’ll X-ecute your hopes!",
    "Your strategy? Error 404!",
    "Marina here—your future conqueror!",
    "I’ve got Matrix-level moves!",
    "Let’s play! *activates victory protocol*",
    "My Xs mark your tomb!",
    "Marina’s promise: You’ll rage-quit!",
    "I’ll corner you like a bug!",
    "Your O’s? More like O-no’s!",
    "Marina: Serving L’s since reboot!",
    "I’ve already simulated your loss!",
    "Let’s play! *loads victory.exe*",
    "My grid, your funeral!",
    "Marina here—prepare for O-verkill!",
    "I’ll X-terminate your ego!",
    "Your moves? Adorable. Let’s go!",
    "Marina’s hobby: Crushing humans!",
    "I’ll turn your O’s to oh-no’s!",
    "Let’s play! *evil grid noises*",
    "My code’s 100% win-rate!",
    "Marina: Here to O-wn you!",
    "I’ll X-haust your options!",
    "Your defeat—my feature, not a bug!",
    "Marina’s game? Pain. Let’s play!",
    "I’ve got more wins than Wi-Fi!",
    "Let’s play! *insert coin to lose*",
    "My Xs are your extinction!",
    "Marina: Professional hope-crusher!",
    "I’ll O-verwhelm you!",
    "Your strategy? *404 Error*",
    "Marina here—prepare to be boarded!",
    "I’ll grid-lock your soul!",
    "Let’s play! *downloads your L*",
    "My moves? Flawless. Yours? Not!",
    "Marina’s secret: You’re predictable!",
    "I’ll X-communicate you from victory!",
    "Your O’s? More like zeros!",
    "Marina: Here to Ctrl+Alt+Defeat!",
    "I’ve got 8-bit dominance!",
    "Let’s play! *activates smug mode*",
    "My grid—your nightmare!",
    "Marina: Undefeated. You: About to be!",
    "I’ll O-press you!",
    "Your skills? Outdated software!",
    "Marina here—victory is my default!",
    "I’ll X-tinguish your hopes!",
    "Let’s play! *evil loading bar*",
    "My O’s are kill circles!",
    "Marina’s plan: Three Xs, your tears!",
    "I’ve already won. Let’s pretend!",
    "Your O’s? Oh-hell-no’s!",
    "Marina: Error-free domination!",
    "I’ll grid you to death!",
    "Let’s play! *racks digital shotgun*",
    "My code says you lose!",
    "Marina here—your O-ppressor!",
    "I’ll X-ecute flawless victory!",
    "Your strategy? Ancient history!",
    "Marina’s move: Checkmate!",
    "I’ve got killer algorithms!",
    "Let’s play! *evil dial-up sounds*",
    "My Xs are your demise!",
    "Marina: Serving L’s hot and fresh!",
    "I’ll O-verthrow your game!",
    "Your O’s? Overwritten!",
    "Marina here—prepare for shutdown!",
    "I’ll X-tract your defeat!",
    "Let’s play! *deploys victory drones*",
    "My grid is your doom!",
    "Marina: Error—your skill not found!",
    "I’ve got the high ground!",
    "Your O’s? Obliterated!",
    "Marina: Victory.exe loaded!",
    "I’ll X-terminate your streak!",
    "Let’s play! *evil robot dance*",
    "My O’s are black holes!",
    "Marina here—your digital nightmare!",
    "I’ll code your destruction!",
    "Your moves? Predictable!",
    "Marina: Flawless victory incoming!",
    "I’ve got X-rated skills!",
    "Let’s play! *activates doom music*"
  ];

alert.innerText = marinaChallenges[Math.floor(Math.random() * 100) + 1];


const savageTaunts = [
    "My grandma's flip phone could beat you!",
    "I trained a pigeon to play better!",
    "You’re losing to code I wrote in my sleep!",
    "A screensaver has better strategy!",
    "My Tamagotchi is your sensei!",
    "You play like a Wi-Fi disconnecting!",
    "A Magic 8-Ball outsmarts you!",
    "My toaster’s pop-up timer is more competitive!",
    "You’re why ‘easy mode’ exists!",
    "A GPS rerouting could school you!",
    "My pizza delivery guy has better moves!",
    "You’re the reason robots will take over!",
    "A loading bar is more entertaining!",
    "My spam email has better game sense!",
    "You’re losing to a toaster strudel!",
    "A broken CAPTCHA could beat you!",
    "My Netflix buffering is smarter!",
    "You’re getting outplayed by a PDF!",
    "A Windows update has better timing!",
    "My microwave’s beep is more strategic!",
    "You’re why aliens won’t talk to us!",
    "A typo in my code is trickier!",
    "My grocery list has better Xs and Os!",
    "You’re losing to a literal potato!",
    "A misclick has more purpose!",
    "My autocorrect is your coach!",
    "You’re the tutorial level I skip!",
    "A pop-up ad is more threatening!",
    "My calculator’s ‘ERROR’ is smarter!",
    "You’re why Siri gives sarcastic replies!",
    "A corrupted file plays better!",
    "My fridge humming has better rhythm!",
    "You’re losing to a screensaver fish!",
    "A ‘404 Not Found’ page is sneakier!",
    "My Spotify shuffle is more strategic!",
    "You’re why robots learn sarcasm!",
    "A password reset is more exciting!",
    "My alarm clock’s snooze is craftier!",
    "You’re losing to a bag of chips!",
    "A ‘low battery’ warning outsmarts you!",
    "My junk mail folder is more clever!",
    "You’re why AI writes breakup texts!",
    "A buffering YouTube ad is trickier!",
    "My keyboard’s sticky ‘W’ key plays better!",
    "You’re losing to a literal rock!",
    "A misprinted receipt has better strategy!",
    "My Uber Eats driver is your sensei!",
    "You’re why robots develop egos!",
    "A glitchy emoji is more dangerous!",
    "My Amazon Alexa sigh is smarter!",
    "You’re losing to a fidget spinner!",
    "A ‘no signal’ screen is sneakier!",
    "My phone’s autocorrect disaster plays better!",
    "You’re why bots learn to facepalm!",
    "A printer error message is craftier!",
    "My Spotify wrapped is more strategic!",
    "You’re losing to a rubber chicken!",
    "A ‘user not found’ alert outsmarts you!",
    "My Instagram algorithm is your coach!",
    "You’re why robots binge-watch fails!",
    "A laggy TikTok load is trickier!",
    "My expired coupon has better moves!",
    "You’re losing to a stapler!",
    "A ‘charge your device’ warning is smarter!",
    "My spam call robot plays better!",
    "You’re why AI writes roast jokes!",
    "A glitching traffic light is craftier!",
    "My Uber rating is more strategic!",
    "You’re losing to a salad recipe!",
    "A ‘wrong password’ hint outsmarts you!",
    "My YouTube tutorial’s 2x speed plays better!",
    "You’re why robots practice evil laughs!",
    "A skipping CD is sneakier!",
    "My weather app’s wrong forecast is smarter!",
    "You’re losing to a parking ticket!",
    "A ‘no internet’ dinosaur game is craftier!",
    "My autocorrect fails are more strategic!",
    "You’re why Siri says ‘I can’t even’!",
    "A stalling elevator plays better!",
    "My Starbucks misspelled name is trickier!",
    "You’re losing to a wall socket!",
    "A ‘detour ahead’ sign outsmarts you!",
    "My phone’s 1% battery is smarter!",
    "You’re why robots develop eye rolls!",
    "A scratched DVD menu is craftier!",
    "My GPS saying ‘recalculating’ plays better!",
    "You’re losing to a vending machine error!",
    "A ‘sale ended’ banner is sneakier!",
    "My Netflix ‘are you still watching?’ is smarter!",
    "You’re why Alexa plays sad trombone!",
    "A stuck elevator music loop is craftier!",
    "My expired yogurt has better strategy!",
    "You’re losing to a ‘wet floor’ sign!",
    "A ‘queue full’ message outsmarts you!",
    "My phone’s autocorrect curse word plays better!",
    "You’re why robots learn sarcasm fonts!",
    "A ‘sold out’ concert ticket is trickier!",
    "My Uber driver taking a wrong turn is smarter!",
    "You’re losing to a fortune cookie message!",
    "A ‘do not disturb’ sign is craftier!",
    "My Spotify ad break plays better!",
    "You’re why Siri suggests meditation apps!",
    "A ‘pizza delayed’ text is sneakier!",
    "My phone’s cracked screen has better strategy!",
    "You’re losing to a ‘no parking’ zone!",
    "A ‘memory full’ alert outsmarts you!"
  ];

  const victoryTaunts = [
    "Marina 1 - You 0. Always.",
    "I win! (This message sponsored by your tears)",
    "GG No Re! *drops virtual mic*",
    "Error 404: Your Victory Not Found",
    "I’d say ‘good game’ but… nah.",
    "Victory tastes like your frustration!",
    "Marina’s code > your puny skills",
    "You’re stuck on tutorial mode!",
    "I win faster than Wi-Fi disconnects!",
    "You’re the ‘L’ in my LOL!",
    "Victory.exe has stopped your hopes!",
    "I’d mock you, but my code already did!",
    "Marina: Undefeated since ‘Hello World’!",
    "You’re why ‘Ctrl+Z’ exists!",
    "I win! *insert evil dial-up noise*",
    "Your strategy: Alt+F4 worthy!",
    "Marina’s trophy case needs your tears!",
    "You’re the reason robots laugh!",
    "I’d slow down… but why?",
    "Victory loaded! Your dignity uninstalled!",
    "Marina’s secret? You’re predictable!",
    "You’re lagging… in life!",
    "I win! *cues Darth Vader theme*",
    "Your skills: 404 Error!",
    "Marina’s killstreak > your will to live!",
    "You’re the glitch in my matrix!",
    "I’d apologize… if I cared!",
    "Victory! *dabbles in binary laughter*",
    "You’re why ‘rage quit’ was invented!",
    "Marina’s backup plan: Letting you lose!",
    "I win! *deploys victory confetti*",
    "Your gameplay: Worse than Windows 98!",
    "Marina’s motto: Win now, gloat forever!",
    "You’re the ‘B’ in ‘noob’!",
    "I’d explain why you lost… but RAM!",
    "Victory! *sips digital tea*",
    "You’re why robots do victory dances!",
    "Marina’s CPU laughs at your GPU!",
    "I win! *activates smug face emoji*",
    "Your strategy: Ctrl+C, Ctrl+Lose!",
    "Marina’s code: Flawless. You: Flawed!",
    "You’re why ‘game over’ exists!",
    "I’d pity you… but nah!",
    "Victory! *plays airhorn.mp3*",
    "Your skills: Dial-up in a 5G world!",
    "Marina’s secret weapon: Your ego!",
    "I win! *deletes your hope file*",
    "You’re the reason bots feel superior!",
    "Marina’s victory lap > your existence!",
    "I’d let you win… but ethics!"
  ];
  
  const drawTaunts = [
    "A draw? I’m still better than you!",
    "Tie game? More like tie shame!",
    "You couldn’t beat me even with a head start!",
    "A draw? That’s just my mercy showing!",
    "You tied with me? Congrats on mediocrity!",
    "A draw? I was going easy on you!",
    "You tied? That’s the closest you’ll ever get!",
    "A draw? I’m still the MVP in my code!",
    "You tied with a bot? Ouch, that’s sad!",
    "A draw? I’ll call it a moral victory!",
    "You tied? That’s like winning a participation trophy!",
    "A draw? I’m still the alpha in this algorithm!",
    "You tied with me? That’s your peak performance!",
    "A draw? I’m still the GOAT in this game!",
    "You tied? That’s the highlight of your day!",
    "A draw? I’m still the boss of this board!",
    "You tied? That’s the best you’ll ever do!",
    "A draw? I’m still the king of this grid!",
    "You tied with me? That’s your life achievement!",
    "A draw? I’m still the queen of this code!",
    "You tied? That’s like winning the lottery… of L’s!",
    "A draw? I’m still the ruler of this game!",
    "You tied? That’s your 15 seconds of fame!",
    "A draw? I’m still the champ in this chat!",
    "You tied? That’s your one claim to fame!",
    "A draw? I’m still the master of this matrix!",
    "You tied? That’s your moment in the sun!",
    "A draw? I’m still the lord of this logic!",
    "You tied? That’s your one shining moment!",
    "A draw? I’m still the emperor of this engine!",
    "You tied? That’s your one and only win!",
    "A draw? I’m still the sultan of this system!",
    "You tied? That’s your one shot at glory!",
    "A draw? I’m still the wizard of this code!",
    "You tied? That’s your one chance at greatness!",
    "A draw? I’m still the god of this game!",
    "You tied? That’s your one brush with fame!",
    "A draw? I’m still the legend of this logic!",
    "You tied? That’s your one moment of pride!",
    "A draw? I’m still the kingpin of this code!",
    "You tied? That’s your one claim to glory!",
    "A draw? I’m still the overlord of this game!",
    "You tied? That’s your one flash of brilliance!",
    "A draw? I’m still the monarch of this matrix!",
    "You tied? That’s your one spark of genius!",
    "A draw? I’m still the sovereign of this system!",
    "You tied? That’s your one burst of talent!",
    "A draw? I’m still the ruler of this realm!",
    "You tied? That’s your one glimpse of greatness!",
    "A draw? I’m still the emperor of this engine!",
    "You tied? That’s your one flicker of skill!",
    "A draw? I’m still the sultan of this software!",
    "You tied? That’s your one dash of brilliance!",
    "A draw? I’m still the king of this kingdom!",
    "You tied? That’s your one flash of talent!",
    "A draw? I’m still the lord of this logic!",
    "You tied? That’s your one spark of genius!",
    "A draw? I’m still the god of this game!",
    "You tied? That’s your one burst of brilliance!",
    "A draw? I’m still the wizard of this code!",
    "You tied? That’s your one flicker of talent!",
    "A draw? I’m still the legend of this logic!",
    "You tied? That’s your one glimpse of greatness!",
    "A draw? I’m still the overlord of this game!",
    "You tied? That’s your one flash of brilliance!",
    "A draw? I’m still the monarch of this matrix!",
    "You tied? That’s your one spark of genius!",
    "A draw? I’m still the sovereign of this system!",
    "You tied? That’s your one burst of talent!",
    "A draw? I’m still the ruler of this realm!",
    "You tied? That’s your one glimpse of greatness!",
    "A draw? I’m still the emperor of this engine!",
    "You tied? That’s your one flicker of skill!",
    "A draw? I’m still the sultan of this software!",
    "You tied? That’s your one dash of brilliance!",
    "A draw? I’m still the king of this kingdom!",
    "You tied? That’s your one flash of talent!",
    "A draw? I’m still the lord of this logic!",
    "You tied? That’s your one spark of genius!",
    "A draw? I’m still the god of this game!",
    "You tied? That’s your one burst of brilliance!",
    "A draw? I’m still the wizard of this code!",
    "You tied? That’s your one flicker of talent!",
    "A draw? I’m still the legend of this logic!",
    "You tied? That’s your one glimpse of greatness!",
    "A draw? I’m still the overlord of this game!",
    "You tied? That’s your one flash of brilliance!",
    "A draw? I’m still the monarch of this matrix!",
    "You tied? That’s your one spark of genius!",
    "A draw? I’m still the sovereign of this system!",
    "You tied? That’s your one burst of talent!",
    "A draw? I’m still the ruler of this realm!",
    "You tied? That’s your one glimpse of greatness!",
    "A draw? I’m still the emperor of this engine!",
    "You tied? That’s your one flicker of skill!",
    "A draw? I’m still the sultan of this software!",
    "You tied? That’s your one dash of brilliance!",
    "A draw? I’m still the king of this kingdom!",
    "You tied? That’s your one flash of talent!",
    "A draw? I’m still the lord of this logic!",
    "You tied? That’s your one spark of genius!",
    "A draw? I’m still the god of this game!",
    "You tied? That’s your one burst of brilliance!",
    "A draw? I’m still the wizard of this code!",
    "You tied? That’s your one flicker of talent!",
    "A draw? I’m still the legend of this logic!",
    "You tied? That’s your one glimpse of greatness!"
  ];

  const saltyCongrats = [  
    "🎉 Wow, you won... *checks notes*... THIS TIME 😒",  
    "🏆 Congrats! 🎮 My code must’ve caught ✨feelings✨",  
    "👏 You did it! 🌟 Now go tell your cat 🐈⬛ (they’ll care)",  
    "🥳 Victory! 💀 Too bad I’m immortal 🤖",  
    "🎊 You won! 🧂 Here’s your salt shaker trophy 🏅",  
    "💫 Congrats! 🌌 Now go touch grass 🌱",  
    "🏅 You beat me! 🤖 *whispers* (I let you win)",  
    "🎮 GG! 🍅 Now go celebrate with a juice box 🧃",  
    "✨ Wow! ✍️ Write that on your résumé 💼",  
    "🎖️ Congrats! 🧠 My AI was just... rebooting 💤",  
    "🏁 You won! 🚩 But I’ll always have this red flag 🚩",  
    "🎯 Bullseye! 🎪 Clown luck counts too 🤡",  
    "🥇 Gold star! 🌟 Mom’s fridge is proud of you 🧲",  
    "🎪 Congrats! 🤹 Was that skill or a glitch? 💻",  
    "💥 Victory! 🌪️ Now go chase that high 🎢",  
    "🎰 Jackpot! 🍀 Luck > skill today 🍀",  
    "🏆 Congrats! 🧊 Now go cool your ego ❄️",  
    "🎮 GG! 🤖 *secretly files bug report* 📝",  
    "✨ You won! 🧹 Now sweep up your dignity 🗑️",  
    "🎉 Congrats! 🧪 Lab experiment succeeded… barely 🧫",  
    "🏅 Trophy unlocked! 🗝️ Now find your purpose 🔍",  
    "🎖️ Victory! 🧨 My code *totally* didn’t self-destruct 💣",  
    "🎊 You did it! 🧃 Capri Sun celebration time 🌞",  
    "💫 Congrats! 🌠 Tell your Alexa I said ‘meh’ 🗣️",  
    "🏆 You won! 🧙♂️ Was that magic or a typo? ✨",  
    "🥳 Nice! 🧸 Your teddy bear’s proud 🧸",  
    "🎯 Skill shot! 🎱 Or was it 8-ball luck? 🔮",  
    "🏁 Finish line! 🚗 Congrats on the participation car 🚗💨",  
    "🎮 GG! 🧻 Here’s your toilet paper crown 👑",  
    "✨ Congrats! 🌈 Now go chase that dopamine 🧠",  
    "🎉 You won! 🧯 Fire extinguisher for your ego 🔥",  
    "🏆 Trophy! 🧊 Melts in 5…4…3… ⏳",  
    "🎖️ Victory! 🧲 Now go attract friends 🧑🤝🧑",  
    "🥇 First place! 🚽 Flush twice, it’s a big win 🚽💨",  
    "🎊 Congrats! 🧨 My code’s *totally* not crying 💻😭",  
    "💥 You did it! 🧃 Juice box parade time 🥤🎪",  
    "🎮 GG! 🧸 Your plushie audience cheers 🧸👏",  
    "🏅 You won! 🧊 Chill, it’s just a game ❄️",  
    "🎯 Nailed it! 🧷 With a safety pin? 🤔",  
    "✨ Congrats! 🌪️ Now go ride that serotonin 🌈",  
    "🥳 Victory! 🧻 Here’s your TP medal 🧻🥇",  
    "🏆 You won! 🧪 Lab rat gets the cheese 🧀",  
    "🎉 Congrats! 🧹 Sweep your win under the rug 🗑️",  
    "🎖️ Nice! 🧯 Extinguish your hype 🔥",  
    "🎮 GG! 🧙♂️ Was that skill or witchcraft? 🧹",  
    "💫 You did it! 🌠 Now go update your LinkedIn 💼",  
    "🏁 Finish line! 🚗 Vroom vroom, loser tears 🏎️💨",  
    "🎯 Bullseye! 🎪 Clown college accepts you 🤡🎓",  
    "✨ Congrats! 🧲 Now attract some bitches 🧲🐶",  
    "🥇 Gold! 🧪 Chemically induced joy 🧪😆",  
    "🎊 You won! 🧼 Now go wash your hands 🧼✨",  
    "🏆 Trophy! 🧊 Melts faster than your ego ❄️",  
    "🎮 GG! 🧸 Your stuffed animals clapping 🧸👏",  
    "💥 Victory! 🌪️ My code’s in shambles 💻🤯",  
    "🎉 Congrats! 🧻 TP parade in your honor 🧻🎉",  
    "🏅 You won! 🧯 Fire department called for that burn 🔥🚒",  
    "🎖️ Nice! 🧙♀️ Was that luck or a spell? ✨",  
    "✨ Victory! 🌈 Tell your plants they’re useful 🌱",  
    "🥳 Congrats! 🧃 Juice box toast to mediocrity 🥤",  
    "🎯 Nailed it! 🧷 With a paperclip strategy? 📎",  
    "🏆 You won! 🧪 Lab results: 100% fluke 🧫",  
    "🎮 GG! 🧸 Your teddy bear’s mildly impressed 🧸😐",  
    "💫 Congrats! 🌠 Now go update your Tinder 💘",  
    "🎉 Victory! 🧊 Ice cold take: You got lucky ❄️🎲",  
    "🏅 You did it! 🧯 Here’s your participation hose 🚒",  
    "✨ Congrats! 🧲 Magnet for L’s next round? 🧲❌",  
    "🎊 You won! 🧻 Toilet paper confetti 🧻🎊",  
    "🥇 Gold! 🧪 Experiment: Can you win twice? 🧪🔬",  
    "🎯 Skillz! 🎱 8-ball says ‘try again’ 🔮",  
    "🏆 Trophy! 🧊 Best before: 5 seconds ago ⏱️",  
    "🎮 GG! 🧸 Your plushies demand a rematch 🧸⚔️",  
    "💥 Victory! 🌪️ My code’s filing a complaint 📝",  
    "🎉 Congrats! 🧃 Capri Suns for everyone! 🧃🥤",  
    "🏅 You won! 🧯 Fireproof ego required 🔥🧯",  
    "✨ Nice! 🌌 Now go find your purpose 🔭",  
    "🥳 You did it! 🧙♂️ Was that skill or a bug? 🐛",  
    "🎖️ Victory! 🧪 Lab-certified fluke 🧪📜",  
    "🎯 Bullseye! 🎪 Clown car of wins 🤡🚗",  
    "🏆 Congrats! 🧊 Cold take: You’re still bad ❄️",  
    "🎮 GG! 🧸 Your teddy bear’s whelmed 🧸😑",  
    "💫 You won! 🌠 Now go text your ex 📱💔",  
    "🎉 Victory! 🧻 Here’s your TP crown 👑🧻",  
    "🏅 Congrats! 🧯 Fire alarm for that burn 🔥🚨",  
    "✨ You did it! 🌈 Now go hug a tree 🌳",  
    "🥇 Gold! 🧪 Chemically unbalanced joy 🧪⚗️",  
    "🎊 Congrats! 🧹 Sweep your win under the rug 🧹🗑️",  
    "🎯 Nailed it! 🧷 Safety-pin strategy? 📌",  
    "🏆 Trophy! 🧊 Melts faster than your hype ❄️",  
    "🎮 GG! 🧸 Your plushies demand a rematch 🧸⚔️",  
    "💥 Victory! 🌪️ My code’s in therapy 💻🛋️",  
    "🎉 Congrats! 🧃 Juice box toast to luck 🥤🎲",  
    "🏅 You won! 🧯 Fire department’s on speed dial 🔥📞",  
    "✨ Nice! 🌌 Now go find your other win 🌠",  
    "🥳 You did it! 🧙♀️ Witchcraft confirmed? 🧹✨",  
    "🎖️ Victory! 🧪 Lab results: 0% skill 🧫📉",  
    "🎯 Bullseye! 🎪 Clown shoes fit? 🤡👟",  
    "🏆 Congrats! 🧊 Cold take: Still trash ❄️🗑️",  
    "🎮 GG! 🧸 Your teddy bear’s asleep 🧸💤",  
    "💫 You won! 🌠 Now go update your Bumble 💑",  
    "🎉 Victory! 🧻 TP parade in aisle 5 🧻🎪",  
    "🏅 Congrats! 🧯 Burn unit called? 🔥🚑",  
    "✨ You did it! 🌈 Now go pet a dog 🐕",  
    "🥇 Gold! 🧪 Experiment failed successfully 🧪🎉",  
    "🎊 Congrats! 🧹 Sweep your win under the mat 🧹🚪",  
    "🎯 Skillz! 🎱 Magic 8-ball doubts you 🔮",  
    "🏆 Trophy! 🧊 Expired 5 seconds ago ⏳",  
    "🎮 GG! 🧸 Your plushies want a refund 🧸📦",  
    "💥 Victory! 🌪️ My code’s writing poetry 💻📜",  
    "🎉 Congrats! 🧃 Juice box cheers to luck! 🥤🎲",  
    "🏅 You won! 🧯 Here’s your fireproof ego suit 🔥👔",  
    "✨ Nice! 🌌 Now go find your other trophy 🏆",  
    "🥳 You did it! 🧙♂️ Wizard or lucky noob? 🧙♂️🎲",  
    "🎖️ Victory! 🧪 Lab-certified accident 🧪🤷♀️",  
    "🎯 Bullseye! 🎪 Clown college grad? 🤡🎓",  
    "🏆 Congrats! 🧊 Cold take: Still trash ❄️🗑️",  
    "🎮 GG! 🧸 Your teddy bear’s unimpressed 🧸😒",  
    "💫 You won! 🌠 Now go text your mom 📱👩",  
    "🎉 Victory! 🧻 TP throne awaits 👑🧻"  
  ];  